"""
XYZ AI Backend — Chat Schemas

Defines Pydantic models for chat API requests and responses.
"""

from typing import Optional
from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    """
    Request payload schema for the AI assistant chat endpoint.
    In prototype, user_id and role are supplied directly.
    """
    user_id: int = Field(..., description="Authenticated user's database ID")
    role: str = Field(..., description="Role of the user: student, parent, teacher, principal")
    message: str = Field(..., description="The text message/query sent to the assistant")
    language: Optional[str] = Field("en", description="Language code for synthesis and processing")

class ChatResponse(BaseModel):
    """
    Response payload schema containing the assistant's output.
    """
    response: str = Field(..., description="The natural language response generated by the assistant")
    audio_base64: Optional[str] = Field(None, description="Optional base64-encoded MP3 audio for speech playback")

